name: CI Checks

# Conditions
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    
jobs:
  tests:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Copy enviroment file
        run: |
          cp .env.example .env && cp .env.testing.example .env.testing

      - name: Run Composer
        run: |
          composer install --no-interaction
          

      - name: Run tests suit
        run: |
          composer test:only

